# Generated by Django 3.0.2 on 2020-04-08 22:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('nightcargoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=100)),
                ('district', models.TextField(max_length=50)),
                ('city', models.TextField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.AlterField(
            model_name='cargo',
            name='delivery_address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nightcargoapp.Address'),
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.ManyToManyField(related_name='address', to='nightcargoapp.Address'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nightcargoapp.Address'),
        ),
    ]
