# Generated by Django 3.0.2 on 2020-04-09 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nightcargoapp', '0004_auto_20200410_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='type',
            field=models.CharField(choices=[('HM', 'Home'), ('WR', 'Work'), ('OT', 'Other')], default='HM', max_length=2),
        ),
    ]
