# Generated by Django 3.0.2 on 2020-04-09 23:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nightcargoapp', '0006_remove_address_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='resident',
        ),
        migrations.AddField(
            model_name='address',
            name='resident',
            field=models.ManyToManyField(related_name='resident', to=settings.AUTH_USER_MODEL),
        ),
    ]
