# Generated by Django 3.0.2 on 2020-04-09 23:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nightcargoapp', '0007_auto_20200410_0246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='resident',
        ),
        migrations.AddField(
            model_name='address',
            name='resident',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resident', to=settings.AUTH_USER_MODEL),
        ),
    ]
