# Generated by Django 3.0.2 on 2020-04-12 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nightcargoapp', '0009_auto_20200412_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cargo',
            old_name='ship_time',
            new_name='time_sent',
        ),
    ]
