# Generated by Django 3.0.2 on 2020-04-14 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nightcargoapp', '0011_auto_20200414_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='date_sent',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='delivery_time',
        ),
        migrations.AddField(
            model_name='cargo',
            name='delivery_day',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31')], default=14, max_length=6),
        ),
        migrations.AddField(
            model_name='cargo',
            name='delivery_hour',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24')], default=21, max_length=6),
        ),
        migrations.AddField(
            model_name='cargo',
            name='delivery_minute',
            field=models.CharField(choices=[('0', '00'), ('1', '05'), ('2', '10'), ('3', '15'), ('4', '20'), ('5', '25'), ('6', '30'), ('7', '35'), ('8', '40'), ('9', '45'), ('10', '50'), ('11', '55'), ('12', '60')], default=20, max_length=6),
        ),
        migrations.AddField(
            model_name='cargo',
            name='delivery_month',
            field=models.CharField(choices=[('1', 'OCAK'), ('2', 'ŞUBAT'), ('3', 'MART'), ('4', 'NİSAN'), ('5', 'MAYIS'), ('6', 'HAZİRAN'), ('7', 'TEMMUZ'), ('8', 'AĞUSTOS'), ('9', 'EYLÜL'), ('10', 'EKİM'), ('11', 'KASIM'), ('12', 'ARALIK')], default=4, max_length=6),
        ),
        migrations.AddField(
            model_name='cargo',
            name='sent_day',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31')], default=14, max_length=6),
        ),
        migrations.AddField(
            model_name='cargo',
            name='sent_hour',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24')], default=21, max_length=6),
        ),
        migrations.AddField(
            model_name='cargo',
            name='sent_minute',
            field=models.CharField(choices=[('0', '00'), ('1', '05'), ('2', '10'), ('3', '15'), ('4', '20'), ('5', '25'), ('6', '30'), ('7', '35'), ('8', '40'), ('9', '45'), ('10', '50'), ('11', '55'), ('12', '60')], default=20, max_length=6),
        ),
        migrations.AddField(
            model_name='cargo',
            name='sent_month',
            field=models.CharField(choices=[('1', 'OCAK'), ('2', 'ŞUBAT'), ('3', 'MART'), ('4', 'NİSAN'), ('5', 'MAYIS'), ('6', 'HAZİRAN'), ('7', 'TEMMUZ'), ('8', 'AĞUSTOS'), ('9', 'EYLÜL'), ('10', 'EKİM'), ('11', 'KASIM'), ('12', 'ARALIK')], default=4, max_length=6),
        ),
    ]
