# Generated by Django 3.0.2 on 2020-04-14 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nightcargoapp', '0013_auto_20200415_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='delivery_address',
            field=models.TextField(default='Boş Adres', max_length=100),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='delivery_minute',
            field=models.CharField(choices=[('0', '00'), ('1', '05'), ('2', '10'), ('3', '15'), ('4', '20'), ('5', '25'), ('6', '30'), ('7', '35'), ('8', '40'), ('9', '45'), ('10', '50'), ('11', '55'), ('12', '60')], default=26, max_length=6),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='sent_minute',
            field=models.CharField(choices=[('0', '00'), ('1', '05'), ('2', '10'), ('3', '15'), ('4', '20'), ('5', '25'), ('6', '30'), ('7', '35'), ('8', '40'), ('9', '45'), ('10', '50'), ('11', '55'), ('12', '60')], default=26, max_length=6),
        ),
    ]
