# Generated by Django 3.0.2 on 2020-04-14 21:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nightcargoapp', '0017_auto_20200415_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='courier',
            field=models.ManyToManyField(related_name='courier', to=settings.AUTH_USER_MODEL),
        ),
    ]
