# Generated by Django 3.0.2 on 2020-04-14 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nightcargoapp', '0018_auto_20200415_0044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cargo',
            old_name='delivery_address',
            new_name='delivery_description',
        ),
        migrations.AddField(
            model_name='cargo',
            name='delivery_city',
            field=models.CharField(default='Eskişehir', max_length=10),
        ),
        migrations.AddField(
            model_name='cargo',
            name='delivery_district',
            field=models.TextField(choices=[('0', 'TEPEBAŞI'), ('1', 'ODUNPAZARI'), ('2', 'SEYİTGAZİ')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='delivery_minute',
            field=models.CharField(choices=[('0', '00'), ('1', '05'), ('2', '10'), ('3', '15'), ('4', '20'), ('5', '25'), ('6', '30'), ('7', '35'), ('8', '40'), ('9', '45'), ('10', '50'), ('11', '55'), ('12', '60')], default=59, max_length=6),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='sent_minute',
            field=models.CharField(choices=[('0', '00'), ('1', '05'), ('2', '10'), ('3', '15'), ('4', '20'), ('5', '25'), ('6', '30'), ('7', '35'), ('8', '40'), ('9', '45'), ('10', '50'), ('11', '55'), ('12', '60')], default=59, max_length=6),
        ),
    ]
